### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by floeshak** [amhummer/Graphinity#1]
Thank you for your research, I was wondering if there are any instructions on how to use the code. Thank you

**Comment by amhummer** [comment]
Hi @floeshak, thank you for your comment. We have provided the code used to develop our EGNN models in the 'src' directory. The 'egnn_model.py' script calls the relevant scripts for eg graph generation and the E_GCL layers. Do you have a specific question about how to use a certain part of the code?

**Comment by ELMIAR-0642** [comment]
> Hi @floeshak, thank you for your comment. We have provided the code used to develop our EGNN models in the 'src' directory. The 'egnn_model.py' script calls the relevant scripts for eg graph generation and the E_GCL layers. Do you have a specific question about how to use a certain part of the code?

Well, I have some doubts. When I was trying to run your code, there were various errors related to version mismatching, I had to make a fresh environment and install every package manually, and you definitely have to remove unnecessary packages from the environment 'yaml' file. Also, the packaging was not good, even after adding directories to `SYSPATH`, `PYTHONPATH`, adding ``os.system(<ADDING CURRENT DIR TO PATH CMD>)`` in the script, the `egnn_model.py` doesn't import modules, so I have to move the scripts out of directories and sub-directories. Well, coming to the main issue, when I tried to write my custom training script I faced all these issues aforementioned, I want to ask you, 

- When will you release the training script?
- Can I use the Data provided in the repo as my training data? (because we don't possess a large storage space to store all of the synthetic datasets)
- Can you release a mini data subset, so people can have a `lite` or `small` version of the model trained?
- Will you update the `README.md` with detailed explanations and instructions?

**Comment by amhummer** [comment]
Hi  @ELMIAR-0642, I am sorry to hear you had difficulties, thank you for letting me know.

I have addressed your questions in the separate issue you raised.
